<<<<<<< Updated upstream
# Generated by Django 4.1.7 on 2023-03-29 11:10
=======
# Generated by Django 4.1.7 on 2023-04-03 15:11
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_menuitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
<<<<<<< Updated upstream
            name='City',
=======
            name='city',
>>>>>>> Stashed changes
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='province',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='street',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
