# Generated by Django 4.1.7 on 2023-04-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
